title: Convo Forums
description: A vibrant online community to share ideas and discuss topics.
baseurl: ""  # NÃ£o usar subpasta
url: "https://convoforums.github.io"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
